apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3 # No of replica needed for pod
  selector: # replica-set labels
    matchLabels:
      app: nginx
      tier: frontend
  template: # pod-definition will start from here
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.18-perl #copied from docker hub