apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  # list of containers
  containers:
  - name: config-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom: # it will take from config-map yaml file
        configMapKeyRef:
          name: devops-config
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-1
spec:
  # list of containers
  containers:
  - name: config-pod-1
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef: # this will refer even 100 key values stored in config-map file, with this single command it can call all
        name: devops-config