apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
type: Opaque
data:
  username: YWRtaW4= # run 'echo -n "admin" | base64' in bash
  password: YWRtaW4xMjM= # run 'echo -n "admin123" | base64' in bash